### PR TITLE
Translation of Python Code Comments and Algorithms from Portuguese to English

### PR DESCRIPTION
**Pull request by Ad1tyaBhardwaj**
A total of 15 files (till dijkstra.py) have been translated to english.
I've thoroughly reviewed and tested the translated code to ensure it functions as intended. The translations have been kept concise and clear to enhance code comprehension. I look forward to your feedback and merging this contribution into the repository. Thank you for considering this pull request.

### CODE REVIEW

**Comment by kelvins** [comment]
Hi @Ad1tyaBhardwaj, thanks for your contribution.
Could you please fix the python linter (CI)?

**Comment by Ad1tyaBhardwaj** [comment]
> Hi @Ad1tyaBhardwaj, thanks for your contribution. Could you please fix the Python linter (CI)?

Sure, I'll do it by tomorrow

**Comment by ricardocarva** [comment]
@Ad1tyaBhardwaj, it looks like there is still something to be fixed. Can you please review the lint checker and update the code?

**Comment by kelvins** [comment]
Closing stale PR (more than 30 days without interactions).
Feel free to reopen it if you still want to contribute. 🍻

**Pull request closed without merging**
