### PR TITLE
Added Selection Sort for C language

### PR DESCRIPTION
**Pull request by JMJ2312**
I have added the C code for Selection sort.

Please add the 'hacktoberfest-accepted' tag.

### CODE REVIEW

**Review by kelvins — CHANGES_REQUESTED** [review]
Hi @JMJ2312, this is the Bubble Sort implementation and it already exists in our repository ([ref](https://github.com/kelvins/algorithms-and-data-structures/blob/main/src/c/BubbleSort.c)).

**Comment by JMJ2312** [comment]
Hi, @kelvins I have corrected the code now

**Comment by kelvins** [comment]
Nice, could you please add the link to the README file?

**Comment by JMJ2312** [comment]
Hi @kelvins, really sorry for the delay. I have added the link in the readme file

**Review by kelvins — APPROVED** [review]

**Pull request merged**
