### PR TITLE
added iterative linear search in java

### PR DESCRIPTION
**Pull request by pluto-tofu**
# Description
Added iterative linear search in Java, which searches for an element in an array using a for loop and returns the index if element is found, else it returns -1.

### CODE REVIEW

**Comment by pluto-tofu** [comment]
@kelvins Could you please review this code, if this is validated by you I will update the Readme file too.

**Comment by pluto-tofu** [comment]
could you approve the workflows, I tried to fix the formatting according to the google java format.

**Comment by kelvins** [comment]
Nice, @pluto-tofu could you please add the link to the README file?

**Comment by pluto-tofu** [comment]
@kelvins I have updated the readme , but I am still getting 
2023-10-24 16:13:47 [ERROR]   Found errors in [google-java-format] linter!
2023-10-24 16:13:47 [ERROR]   Error code: 1. Command output:
in the Lint Checker test. Could you please help me to resolve this?

**Comment by pluto-tofu** [comment]
@kelvins I have tried to fix the formatting again, could you please run the tests.

**Comment by pluto-tofu** [comment]
@kelvins Sorry but the test is still failing due to the same reason, I have used black to format python files in the past but I'm not able to pinpoint what is wrong in this case.

**Comment by kelvins** [comment]
> @kelvins Sorry but the test is still failing due to the same reason, I have used black to format python files in the past but I'm not able to pinpoint what is wrong in this case even though I have formatted the file correctly.

No worries, I'll try to fix it.

**Review by kelvins — APPROVED** [review]
Thanks @pluto-tofu 🚀

**Pull request merged**
