### PR TITLE
Translate Go algorithm comments from Portuguese to English

### LINKED ISSUE #184: Translate Go algorithms and comments to English.
Please help translate the algorithms and comments in Go from Portuguese to English, as this would help increase the visibility of the repository, and it's the standard used by the company/people.

--

Por favor ajudem a traduzir os algoritmos e comentários em Go do português para o inglês, pois isso ajudaria a aumentar a visibilidade do repositório, e é o padrão utilizado por empresa/pessoas.

### PR DESCRIPTION
**Pull request by K11E3R**
### Summary

Translated comments, variable names, and function names in Go algorithm files from Portuguese to English.

### Details

- **Comments**: Updated all comments to English to improve readability for English-speaking developers.
- **Variable Names**: Renamed variables from Portuguese to English to align with common coding conventions and enhance code clarity.
- **Function Names**: Renamed functions from Portuguese to English to maintain consistency and readability.
- **Code**: No functional changes to the code; only identifiers and comments were modified.

### Related Issues

- Closes #184

### CODE REVIEW

**Review by K11E3R — COMMENTED** [review]
### Summary

Translated comments, variable names, and function names in Go algorithm files from Portuguese to English.

### Details

- **Comments**: Updated all comments to English to improve readability for English-speaking developers.
- **Variable Names**: Renamed variables from Portuguese to English to align with common coding conventions and enhance code clarity.
- **Function Names**: Renamed functions from Portuguese to English to maintain consistency and readability.
- **Code**: No functional changes to the code; only identifiers and comments were modified.

### Related Issues

- Closes #184

**Review by K11E3R — COMMENTED** [review]
- *Done reviewing ✅*

**Review by K11E3R — COMMENTED** [review]
- *Done reviewing ✅ all files*

**Review by kelvins — APPROVED** [review]
Nice, thank you so much @K11E3R!

**Review by K11E3R — COMMENTED** [review]
func print => func show

full code updated ✅

**Review by kelvins — APPROVED** [review]

**Pull request merged**
