### PR TITLE
Translated Portuguese comments and added English comments alongside i…

### PR DESCRIPTION
**Pull request by Abhiharsh-IN**
# Description

Translated Portuguese comments and added English comments alongside in Dijkstra.java file to make it help increase the visibility of the repository.

### CODE REVIEW

**Comment by Abhiharsh-IN** [comment]
@ricardocarva Please review it.

**Review by kelvins — CHANGES_REQUESTED** [review]
Thanks @Abhiharsh-IN! The objective of this task is to replace the pt-br comments, not just append the english version. Could you please fix it? Also its important to make sure the CI is passing before we can review and merge the PR.

**Comment by Abhiharsh-IN** [comment]
I will update the code asap. @kelvins

**Review by kelvins — APPROVED** [review]
Nice, thanks @Abhiharsh-IN!

**Comment by Abhiharsh-IN** [comment]
My pleasure sir

**Comment by Abhiharsh-IN** [comment]
@kelvins Shall I do add English comments to the java codes which are not having the proper comments . I would be really happy to contribute in that too.

**Pull request merged**
